name: E2E on Chrome

on: 
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        continue-on-error: true
        run: npm run cy:run
